# NOTE(sileht): Don't touch this file, it should be in sync with:
# https://ghes-dev.mergify.com/mergifyio-testing/.github/blob/main/.mergify.yml
defaults:
  actions:
    queue:
      name: default

queue_rules:
  - name: default
    conditions:
    - check-success=test


pull_request_rules:
  - name: automatic queue
    conditions:
      - base=main
      - label=automerge
    actions:
      queue:
