defaults:
  actions:
    comment:
      bot_account: mergify-ci-bot

pull_request_rules:
  - name: comment with default
    conditions:
      - label=comment
    actions:
      comment:
        message: I love Mergify
